all:cave

cave: cave.cpp 
	g++ -g -Wall -std=c++11 cave.cpp -o cave 

permutations: permutations.cpp 
	g++ -g -Wall -std=c++11 permutations.cpp -o perm

company:company.cpp company.hpp
	g++ -g -Wall -std=c++11 company.cpp -o company
 
